name: deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: node18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build and Deploy
        run: |
          npm install
          npm run build

      - name: 'commit'
        run: |
          git config --local user.email "w431106@163.com" 
          git config --local user.name "stbui"
          git add .
          git commit -m "render template"

      - name: 'push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
